import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import BottomNav from "@/components/BottomNav/BottomNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "GIA Stocks",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={`${inter.className} bg-gray-100 relative`} id="root">
            <header>
               <Navbar></Navbar>
            </header>
            {children}
            <BottomNav></BottomNav>
         </body>
      </html>
   );
}
